name: car_appp_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  bot_toast: ^4.1.3
  cloud_firestore: ^6.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
