// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAciMEOt43ikdbERxjEEMMrZmmGnLme5o',
    appId: '1:1072725251889:web:286150ac0be0d72c218210',
    messagingSenderId: '1072725251889',
    projectId: 'carapp-608d1',
    authDomain: 'carapp-608d1.firebaseapp.com',
    storageBucket: 'carapp-608d1.firebasestorage.app',
    measurementId: 'G-PS2FFNMYTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtaaUg3omm7qbWmdzpLdG6pw9UzD9LTRU',
    appId: '1:1072725251889:android:cdc94e41427b0c77218210',
    messagingSenderId: '1072725251889',
    projectId: 'carapp-608d1',
    storageBucket: 'carapp-608d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PGdhcECsmiWn9r5gqZGjihE686vPQvA',
    appId: '1:1072725251889:ios:a30c408cd6a42d9e218210',
    messagingSenderId: '1072725251889',
    projectId: 'carapp-608d1',
    storageBucket: 'carapp-608d1.firebasestorage.app',
    iosBundleId: 'com.example.carApppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PGdhcECsmiWn9r5gqZGjihE686vPQvA',
    appId: '1:1072725251889:ios:a30c408cd6a42d9e218210',
    messagingSenderId: '1072725251889',
    projectId: 'carapp-608d1',
    storageBucket: 'carapp-608d1.firebasestorage.app',
    iosBundleId: 'com.example.carApppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAciMEOt43ikdbERxjEEMMrZmmGnLme5o',
    appId: '1:1072725251889:web:f7032cf3696d78a4218210',
    messagingSenderId: '1072725251889',
    projectId: 'carapp-608d1',
    authDomain: 'carapp-608d1.firebaseapp.com',
    storageBucket: 'carapp-608d1.firebasestorage.app',
    measurementId: 'G-7HENGXXBYK',
  );

}